### ISSUE TITLE
Restructuring FDZ data cleaning vignette

### ISSUE THREAD

**Issue by beckerbenj** [beckerbenj/eatFDZ#6]
Currently the vignette is rather loosely structured. I think I would prefer if the vignette would state explicitly the conceptual goals of the data cleaning (anonymization, approrpriate missing tags, ...) and then it is simply illustrated how to achieve these goals.

I have started to move the vignette in this direction in the `dataCleaningVignette` branch. Could you check it out and, if possible, pick it up from there? Feel free to set up a meeting when you return from vacation to discuss things!

**Comment by ruckeran** [comment]
Tomorrow I want to start working on the vignette. I've already had a look at it and have written down that I'll pay more attention to the following steps: 1. what is the goal there? 2. how is it achieved? and that I generally write more in a passive form and focus on the R functions. Correct?

**Comment by beckerbenj** [comment]
Sounds good to me!
